- hosts: all 
  tasks:
  - name: install the latest version of Apache
    yum:
      name: 
        - httpd
        - git
        - wget
      state: latest
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
      enabled: yes 


  - name: stop httpd
    service:
      name: httpd
      state: stopped

  # - name: Remove git
  #   service:
  #     name: git
  #     state: absent
 