- hosts: all 
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
    register: hello
    ignore_errors: yes


  - name: Start apache
    service:
      name: httpd
      state: started
    register: kaizen



  - debug: msg={{ hello }}
  - debug: msg={{ kaizen }}